version: '2'
services:
  db:
    build:
      context: .
      dockerfile: Dockerfile.db
    environment: 
      POSTGRES_PASSWORD: my-password
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    restart: unless-stopped

  web:
    build: .
    volumes:
      - .:/myapp
    ports:
      - "3002:3000"
    environment:
      PLAID_CLIENT_ID:
      PLAID_SECRET:
      PLAID_PUBLIC_KEY:
      PLAID_ENV: 'development'
      PLAID_PRODUCTS: 'transactions'
      PLAID_COUNTRY_CODES: 'US,CA,GB,FR,ES'
    depends_on:
      - db
    restart: unless-stopped

  notebook:
    build:
      context: notebook/
    ports:
      - 8888:8888
    volumes:
      - ./notebook/work:/home/jovyan/work
    depends_on:
      - db
