version: '2'
services:
  db:
    image: postgres:13
    environment: 
      POSTGRES_PASSWORD: my-password
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
      - ./prod_backup.sql:/docker-entrypoint-initdb.d/prod_backup.sql
      - ./:/myapp
    restart: unless-stopped

  web:
    build: .
    volumes:
      - .:/myapp
    ports:
      - "3002:3000"
    environment:
      PLAID_CLIENT_ID:
      PLAID_SECRET:
      PLAID_PUBLIC_KEY:
      PLAID_ENV: 'development'
      PLAID_PRODUCTS: 'transactions'
      PLAID_COUNTRY_CODES: 'US,CA,GB,FR,ES'
      MAILGUN_USER:
      MAILGUN_PASSWORD:
      DATABASE_URL: postgres://postgres:my-password@db:5432/postgres 
    depends_on:
      - db
    restart: unless-stopped

  notebook:
    build:
      context: notebook/
    ports:
      - 8888:8888
    volumes:
      - ./notebook/work:/home/jovyan/work
    depends_on:
      - db
